### PR TITLE
Create Policies.md

### PR DESCRIPTION
**Pull request by Reenhaider**
## Network Configuration

1. Cable up PA-220 according to diagram above.
2. Modify MGMT PC’s
  IP address (192.168.1.20), mask and default gateway according to diagram
3. Download
  server .vmdk file from S drive to VM HOST PC to host DMZ server (Linux Ubuntu
  64bit, 4 gig RAM)
4. Allocate DMZ VM
  HOST PC host an IP of 192.168.50.2
5. Configure DMZ
  server to run in Virtual box bridged mode (username: steve  password: Password1) (Static IP , GW and
  DNS settings have been pre-configured)
6. Use MGT PC to
  set up PA-220 on https://192.168.1.1/
7. Modify Client
  PC’s IP address (192.168.XX.20), mask and default gateway according to
  diagram - Where **XX** is your MGMT
  PC # in classroom (eg 1 – 24)
8. Set Client PC’s DNS IP addresses to 192.168.210.2 and 8.8.8.8

## Configure Networking

Complete the following objectives:

  Note: On a new device there may be a trust security policy, virtual
wire object, 2 virtual wire zones that need to be deleted

  Ensure there are no existing Security / NAT policies, zones or
virtual wire objects set – delete them if they exist and commit

  Configure three firewall interfaces using the following values:

  **Ethernet 1/1**: 192.168.208.2XX/24 - Layer 3

  **Ethernet 1/2**: 192.168.XX.1/24 - Layer 3

  **Ethernet 1/3**: 192.168.50.1/24 - Layer 3

  **Management:** 192.168.1.1/24

  Create a virtual router called VR-1 for all configured firewall interfaces.

  Create a default route for the firewall called Default-Route (next hop to ISP – ie
0.0.0.0/0 to 192.168.208.1

  Create an Interface Management Profile called Allow-ping that allows ping

  Assign the Allow-ping Interface Management Profile to ethernet1/2

## Configure Security Zones

Complete the following objectives:

  Create a Security Zone called Internet and assign ethernet1/1 to the zone

  Create a Security Zone called Users and assign ethernet1/2 to the zone:

  Configure the **Users Zone** for User-ID

  Create a Security Zone called Extranet and assign ethernet1/3 to the zone

  Create Tags for each Security Zone using the following names and colors:

  Extranet –
orange

  Internet –
black

  Users –
green

## Verify Network Connectivity

Verify
network connectivity from the firewall to other hosts.

  Your internal host can ping 192.168.XX.1 and receive a response

  Run Putty SSH client and
connect to 192.168.1.1 , login with firewall credentials (admin,Password1) to
get a CLI prompt

  From the firewall CLI, the
following commands are successful:

  ping source 192.168.208.2XX host 192.168.208.1

  ping source 192.168.208.2XX host 8.8.8.8

  ping source 192.168.XX.1 host 192.168.XX.20

  ping source 192.168.50.1 host 192.168.50.2

  ping source 192.168.50.1 host 192.168.50.100

   

## Configure NAT

Policy Rules

Create Source NAT rules to meet the
following requirements:

  Rule Name = Users_to_Internet

  From Source Zone Users to Destination Zone Internet

  Use ethernet1/1 on the firewall as the source translation address

  Tag = Users

  Rule Name = Extranet_to_Internet

  From Source Zone Extranet to Destination Zone Internet

  Use ethernet1/1 on the firewall as the source translation address

  Tag = Extranet

  All NAT rules must include a helpful Description

## Configure Security Policy Rules

Create
Security policy rules to meet the following requirements:

  For all Security policy rules, enter a helpful Description.

  Create and apply the following Tags to
the Security policy rules as appropriate:

  Allow –
Lime

  Block – Red

  Modify the interzone-default Security policy
rule so that traffic is logged at session end.

  Create a Security policy rule called Block_Bad_URLs with the following characteristics:

  For all outbound traffic, the URL categories hacking, phishing, malware,
and unknown must be blocked by a Security policy rule
match criterion.

  From the User zone to the Extranet zone, create a Security policy
rule called Users_to_Extranet to allow the following applications:

  ping

  ssl

  ssh

  dns

  web-browsing

  From the User zone to the Internet zone, create a Security policy
rule called Users_to_Internet to allow the following applications:

  ping

  dns

  web-browsing

  ssl

  From the Extranet zone to the Internet zone, create a Security
policy rule called Extranet_to_Internet to allow the following applications:

  ping

  dns

  web-browsing

  ssl

You can consider this objective complete
when the following tests are successful:

  The client host can ping 8.8.8.8 and google.com

  The client host can access [www.paloaltonetworks.com](http://www.paloaltonetworks.com/)

  The client host can browse to the Extranet web server at http://192.168.50.100/

  The client host can use SSH to access
the Extranet host at 192.168.50.100 using the login name steve and the password Password1

  The Extranet host can ping 8.8.8.8 and google.com

  The internal host cannot access hacker9.com

## Create and Apply Security Profiles

Create Security Profiles and a Security
Profile Group to meet the following requirements:

  A Corporate URL Filtering Security Profile called Corp-URL to log access to all web categories

You can use the existing default profile
as the basis for your own

  A Corporate File Blocking Security Profile called Corp-FB to block dangerous file types

You can use the existing strict profile as
the basis for your own

  A Corporate Antivirus Security Profile called Corp-AV to block viruses

You can use the existing default profile
as the basis for your own

  A Corporate Anti-Spyware Security Profile called Corp-AS to block viruses

You can use the existing strict profile as
the basis for your own

  A Corporate Vulnerability Protection Security
Profile called Corp-Vuln to block viruses

You can use the existing strict profile as
the basis for your own

  A Corporate WildFire Profile called Corp-WF to
send all file types to the public cloud for inspection

 You
can use the existing default profile as the basis for your own

  Create a Security Profile Group called Corp-Profiles and assign the appropriate Security Profiles to it

**Note:** You
can leave the Data Filtering Profile set to **None**.

  Apply the Corp-Profiles Group to all
applicable Security policy rules

You can consider this objective complete
when the following tests are successful:

  The internal host cannot download a test virus file from [www.eicar.org](http://www.eicar.org/) using HTTP.

  The internal host cannot download the badtarfile.tar from http://192.168.50.100/badtarfile.tar

  A URL log file entry appears when the client host browses to [https://www.paloaltonetworks.com/](https://www.paloaltonetworks.com)

  Note this will require a custom url category added to corp_url and
set to generate an alert that will appear in the URL log monitor

## Configure Security and NAT policy to Access DMZ server

from Internet

Reference

### Part 1 – Configure destination NAT policy and security

policy

Enable remote web access (port 80) to DMZ
server from the internet Zone (E208 PCs)

**Add
a NAT policy:**

Source Zone: Internet

Destination Zone: Internet

Destination Interface: Any

Source Address: Any

Destination Address: 192.168.208.1**XX**

Service: service-http   (change to any to allow SSH, RDP, 3306)

Source translation: None

Destination Translation: destination-translation
address 192.168.50.100

**Add
a security policy:**

Source Zone: Internet

Source address: Any - (add for part 2 -
192.168.208.YY)

Destination Zone: Extranet

Destination Address: 192.168.208.1XX

Application: Web-Browsing (add for part 2 - to allow SSH, ms-rdp,
3306)

Service: Application-default

Action: Allow

**Test
http from an Internet PC on E208 Network (E208 PC):**

[**http://192.168.208.1xx/**](http://192.168.208.1XX)

### Part 2 - Configure and test remote management

Enable remote management access to DMZ
server from the Internet Zone from only 1 specific IP address (E208 PC) – for
SSH , Remote Desktop Protocol (RDP) , and MySQL remote administration (port
3306).

**Clone
and Modify firewall part 1 security policy to:**

**1.**     **allow all access to 192.168.208.1XX  on port 80 only**

**2.**     **allow ssh , RDP and port 3306 to 192.168.208.1XX  from a single Internet PC IP address in E208
Network**

**3.**     **modify NAT policy for service any**

**Test
rdp from an E208 PC on E208 Network to 192.168.208.1XX**

**Test
ssh (putty) from an E208 PC on E208 Network to 192.168.208.1XX**

**Run
nmap from an E208 PC on E208 Network to 192.168.208.1XX**

# Document steps involved in implementing parts 1 and 2, with

all testing procedures and results - upload to Gordon online

## Notes

Notes for testing access from single
Internet IP address ensure ssh and xrdp atr added to the dmz server:

$sudo apt install xrdp

$ sudo /etc/init.d/xrdp restart

$sudo apt install openssh-server

$ sudo systemctl enable ssh

## Create MySQL remote user account

http://localhost/phpmyadmin  
New > User accounts  
User account 'I40Remote'@'%' (any Host) OR 'I40Remote'@'X.Y.Z.A'  
grant SELECT Data privileges only  
NOTE: I40Remote needs to use the Authentication plugin =
auth_plugin='mysql_native_password'

## Config MySQL and firewall rules for remote connections on port

3306

https://www.digitalocean.com/community/tutorials/how-to-allow-remote-access-to-mysql

`$sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf`  
Change the bind address – note security issues – this should be a static IP in
production

eg.  
`$ip a`  
192.168.50.100 - server ip address  
change the bind address to server address ie 192.168.50.100

This will allow connectivity from a remote windows host that will
be analyzing data

You will now be able to make remote connections to MySQL on port
3306 from your E208 PC using MySQL workbench

### CODE REVIEW

**Comment by Reenhaider** [comment]
Hi team, Can you please review firewall confguration.

**Comment by jarnaks** [comment]
Hi Shehreen,
Hope all is well at home and you got some sleep!

Not sure what you want reviewed or what I have been assigned. Maybe too
early in the morning for me?
The md doc is saying it is closed.

Also, just a few questions & updates..
For the ICTPRG Software project I have put all my sections into the
domain_blocker repo, pseudocode, flowchart, testing & debugging, and the
user documentation in the readme.md file so our main doc in google docs
will largely be a set of links? Is this fine with everyone?
 I still have a bit of tweaking to do as there is still the some technical
section to do... I am not sure what to write here as there is already so
much comment and documentation.

For our Cyber Project monthly production report we have not had a formal
meeting for this. On Thursday, Steve said that we will have our final
monthly meeting next week and in our final week we will have our 'project
closing' meeting.
So what is meant to be handed in on Sunday? I think our final production
report should be closed to project finish with the 'Evaluation stage' at
least in progress. I am happy to hand this report in after our meeting next
week. What do you think guys?

Sorry, to throw all these questions at you Shehreen,  but I know you
mentioned you have a religious holiday tomorrow.

Just let me know what needs to be done.

Cheers,
Jarna

**Comment by Reenhaider** [comment]
Hi Jarna,

Sorry, I should have sent you all an email about the purpose of the link
earlier. The reason I did it is that I've mentioned in our GitHub
collaboration document that we use GitHub Code Review functionality for
peer review when we pull requests for code/documents. Also, we can
screenshot that and include it in our document.

For the ICTPRG Software project, I suggest we include the mermaid flowchart
and pseudocode in the document (we can also include the link under
appendices).

For our Cyber Project monthly production report, since we haven't had a
meeting yet, I would suggest holding off on this report and submitting it
after our meeting next week.

Sorry, everyone, I am heading off now. I'll need to work on the assessments
after I come back home tonight. Meanwhile, please keep me updated or email
me if you need anything from me.

Cheers!

**Comment by jarnaks** [comment]
Sounds good!

**Pull request closed without merging**
